### ISSUE TITLE
JsonProtocol Refactor Phase 2 - Switch to Lib3hProtocol

### ISSUE THREAD

**Issue by zippy** [holochain/lib3h#102]
As a lib3h client, I can now stop using JsonProtocol and switch to Lib3hProtocol, so that my transition from n3h to lib3h is staged.

Dependencies:
- #81 

Tasks:
- [x] @struktured: Delete unnecessary tests in test-bin in the core net-crate use Lib3hProtocol and have all tests pass
- [X] @lucksus  @struktured: App-spec tests
- [X] @lucksus Refactor core to use new Lib3hProtocol
- [X] @neonphog (neo4g): Update n3h to use Lib3hProtocol
- [x] releasing for HoloChain core
- [X] @lucksus help fix failing tests (none found)

Acceptance Criteria:
- All existing in core tests pass

**Comment by chrisgagne** [comment]
Blocked due to the rust versioning issues we've been having
