### ISSUE TITLE
Spike: Land Repo Dependency Process for lib3h-protocol crate/repo

### ISSUE THREAD

**Issue by zippy** [holochain/lib3h#128]
- [ ] create a process for the repo-depenencies that this will create around changes to lib3h-protocol crate.

Draft: https://hackmd.io/UjqdQCHcQ2m-fSIgtaGAvQ

Acceptance Criteria:

- We have an agreed upon protocol for with core devs on the repo/crate-dependancy process for updating versions

**Comment by ddd-mtl** [comment]
@zippy We might need to distinguish update types according to semver (major, minor, patch)
