### ISSUE TITLE
Spike: Figure out ALM tooling

### ISSUE THREAD

**Issue by zippy** [holochain/lib3h#160]
We answer the following question:

- [ ] is there a way for us to use Pivotal Tracker for it's PM benefits and still keep two way flow to github for Open Source visibility
- [x] is it worth looking at other e.g. tools (gitlab)
- [ ] How do we capture technical data and specifications

Background info: PT/GH integration: https://www.pivotaltracker.com/help/articles/github_integration/
We can get 1:1 video support from Pivotal Tracker:  https://app.hubspot.com/meetings/pgraham

- [x] @neonphog Looked at Gitlab, not much better than Github
- [ ] evaluate https://www.zenhub.com/ - seems to support a lot of things waffle did, and is free for public repos / supports burndowns/velocity tracking and epics we could use as userstories if we wanted issues to be more task-level
- [ ] Meeting b/t Pivotal support, @neonphog, @chrisgagne, @jmday

**Comment by chrisgagne** [comment]
To be discussed on TUesday
