### ISSUE TITLE
[IN-MEM] SPIKE - evaluate persistence options (like sqlite3) with an eye towards indexing / lru caching requirements for lib3h

### ISSUE THREAD

**Issue by neonphog** [holochain/lib3h#17]
We need to choose a database to persist content addressable data and have indexes over the data. This research should be time boxed and whatever product is chosen should be encapsulated within a persistence interface so we can try alternative implementations later.

The schema should consider different layers which have different key value associations.
 
- peer layer
    - key: machine id
    - value:```{transport_address:wss://...}```
- app/dna layer
    - key: tuple of dna hash and agent id
    - value: machine id

**Comment by struktured** [comment]
[Hackmd](https://hackmd.io/u3MgMRQDStCY5ra-1UQuFQ?both) to build some notes on database choices.
