### ISSUE TITLE
SPIKE: Come up with a staged approach to debugging

### ISSUE THREAD

**Issue by jmday** [holochain/lib3h#223]
Acceptance criteria:

* We have designed a staged approach to debugging and created backlog items for implementation
* Figure out upcoming backlog items around Walkman,  tracing, and State transition visibility
* Coordinate with other teams that may have this issue (e.g., tracing is a cross-cutting issue now)

Targeting about 2 hours of meeting, we'll regroup if we don't come to a solution at that point.

**Comment by zippy** [comment]
approach is embodied by the current epics
