### ISSUE TITLE
BUG: log filtering bug when running app-spec

### ISSUE THREAD

**Issue by zippy** [holochain/lib3h#244]
Filtering doesn't seem to work.  Steps to reproduce:

check out `lib3h-client-protocol-integration-transport-memory` of holochain-rust and run:

```
hc-app-spec-test-memory
```

After compilation and as soon as you start seeing logging output you can control-c out of the process.

Now, you can edit the file in which the conductor configuration is created `app_spec/test/spawn_conductor.js`:

Change:

```
[logger]
type="debug"
${debugging ? '' : '[[logger.rules.rules]]'}
${debugging ? '' : 'exclude = true'}
${debugging ? '': 'pattern = "^debug"'}
state_dump = true
```

to

```
[logger]
type="debug"
[[logger.rules.rules]]
exclude = true
pattern = "^lib3h.*"
color = "red"
${debugging ? '' : '[[logger.rules.rules]]'}
${debugging ? '' : 'exclude = true'}
${debugging ? '': 'pattern = "^debug"'}
state_dump = true
```
Now finally you can run the tests again with out using holonix (and thus avoiding the recompile with:

```
cd app_spec/test
APP_SPEC_NETWORK_TYPE='memory' npm run test-ci
```

**Comment by dymayday** [comment]
Thanks for reporting the issue, it's fixed here https://github.com/holochain/holochain-rust/pull/1654 :)
