### ISSUE TITLE
[REPO] move and clarify enumerated endpoints to `Lib3hProtocol` (formerly JsonProtocol)

### ISSUE THREAD

**Issue by jmday** [holochain/lib3h#27]
As a lib3h client, I can know the enumerated endpoints in the `Lib3hProtocol` (formerly JsonProtocol) so that I have knowledge of the protocol.

- [x] Discuss path forward with HC Core team
- [x] We have a method of knowing the alterations that have been made to JsonProtocol
- [x] We need to maintain the n3h connection
- [x] JsonProtocol is imported from core && all changes are tracked

Scoping:
- Does not required completion CheckHealth, AdvancedQuery

**Comment by zippy** [comment]
The principle artifact of this work is here: https://hackmd.io/ZZ9wJFPHQxqIz4lOCkocTQ?view
