### ISSUE TITLE
[REPO] build basic tooling: core dependencies switch

### ISSUE THREAD

**Issue by jmday** [holochain/lib3h#28]
As a networking developer, I can rely on basic tooling for dev work so that I don't get annoyed with wasting time doing mundane things over and over (and over). 

- [ ] SPIKE: Easily switch core dependencies back and forth between crates.io and local path refs
  - (… would be nice if we had https://github.com/rust-lang/rfcs/pull/2678)

**Comment by neonphog** [comment]
https://hackmd.io/eGD2oR6ZSLCBJa7e_uWvPA

**Comment by neonphog** [comment]
Waiting on review: https://github.com/holochain/holochain-rust/pull/1442

**Comment by neonphog** [comment]
recommendation documented. Please see https://github.com/holochain/holochain-rust/blob/develop/doc/dependency_dev_pattern.md for procedure.
