### ISSUE TITLE
GhostActor Test Generalization

### ISSUE THREAD

**Issue by jmday** [holochain/lib3h#286]
We should generalize the concepts of the existing real engine processor harness (`processor_harness.rs`) for ghost actors. Useful functions would be:
- [x] `wait_for_callback`: given a regular expression predicate over callback data and a ghost actor, verify the ghost call back is triggered and the regular expression matches or fail after an arbitrary number of calls to process 
- [x] `wait_for_messages`: given a regular expression predicate over the drain messages and a set of ghost actors with a tracker (eg. `GhostCanTrack`), verify the given regular expressions matches or fail after an arbitrary number of calls to process. 
- [x] `wait_did_work`/`wait_ghost_can_track_did_work`: call process on ghost actor(s) and verify work was actually done
- [x] `wait_until_no_work`/`wait_ghost_can_track_until_no_work`: call process on ghost actor(s) until `WorkWasDone` is false
- ~~~`assert_eq`: similar to `assert_callback` but checks that a context or user data is equal to some expected value~~~. (Not necessary in favor of more general regex style verification)

**Comment by struktured** [comment]
We should generalize the concepts of the existing real engine processor harness (`processor_harness.rs`) for ghost actors. Useful functions would be:

- `assert_callback`: given a `GhostCallback` and a ghost actor, verify the ghost call back is triggered or fail after an arbitrary number of calls to process 
- `wait_did_work`: call process on ghost actor(s) and verify work was actually done
- `wait_until_no_work`: call process on ghost actor(s) until `WorkWasDone` is false
- `assert_eq` : similar to `assert_callback` but checks that a context or user data is equal to some expected value.

**Comment by struktured** [comment]
Related PRs:

https://github.com/holochain/lib3h/pull/382
https://github.com/holochain/lib3h/pull/367
https://github.com/holochain/lib3h/pull/355
https://github.com/holochain/lib3h/pull/314
