### ISSUE TITLE
[REPO] Stub Lib3h to poll and listen for emitted Protocol messages

### ISSUE THREAD

**Issue by jmday** [holochain/lib3h#30]
As a lib3h client, I can call a stubbed Lib3h and poll for emitted Lib3hProtocol messages so that I can test general integration.

- [x] lib3h stub that can receive lib3hProtocol messages
- [x] lib3h stub that can poll for emitted Lib3hProtocol messages as events/signals

**Comment by ddd-mtl** [comment]
`Lib3hProtocol` is Lib3h's "what we want' protocol between Core and a network module whereas `P2pProtocol` is for communication between network modules, which includes gossiping.

`net` crates stays in Core repo and keeps the Worker code and net connection thread code.
Workers are our current interface between Core and whatever type of network module (in-memory, n3h, lib3h).
We plan to swap out `JsonProtocol` in favor of `Lib3hProtocol` in the top layer `Protocol`.
For now Lib3hWorker can do the translation between these two protocols?
