### ISSUE TITLE
[REPO] lib3h crate published to crates.io

### ISSUE THREAD

**Issue by jmday** [holochain/lib3h#32]
As a lib3h client, I can import lib3h from crates.io so that rust development with lib3h is super easy

- [ ] document crates.io publishing strategy
  - We want to have a process documented to be followed when publishing
- [ ] lib3h crates are published to crates.io
  - Initial versions of lib3h crates are published to crates.io

**Comment by neonphog** [comment]
Closing this as `lib3h_crypto_api` and `lib3h_sodium` are published. We have a pattern we can follow when the other crates are ready to be published.
