### ISSUE TITLE
[REPO] Point holochain conductor at lib3h crates from crates.io

### ISSUE THREAD

**Issue by jmday** [holochain/lib3h#33]
As a Holochain conductor, I can import crates from crates.io so that I can use that functionality.

- [ ] core points to `lib3h_crypto_api`
- [ ] core points to `lib3h_sodium` crate

**Comment by neonphog** [comment]
updating because we are pointing core at `lib3h_crypto_api` and `lib3h_sodium`. We have a pattern now that we can implement when the other crates are mature enough to be imported.
