### ISSUE TITLE
Use mDNS for local node discovery

### ISSUE THREAD

**Issue by jmday** [holochain/lib3h#52]
As a lib3h client, I can connect to other local peers via MDNS, so that no work is required for bootstrapping peers during hackathons and in development (app_spec with real networking needs to rely on local discovery).

Based on SPIKE #85 results: Potential for engagement of open source community contribution to mature the crate. Consider creation of repo and use of bounties to engage code contributions? 

SEE PROTOTYPE CODE: Prototype code: https://github.com/holochain/lib3h/compare/mdns

- [X] @dymayday in process: learning about mDNS
- [x] Create Discovery Trait
- [x] Configuration for mdns
- [X] implement mdns (based on mdns library chosen in spike above)
- [x] impl communications
- [X] impl protocol
- [x] impl neighbor caching

Acceptance Criteria:
- we have a test that shows that nodes find each other using the chosen mdns crate.

**Comment by neonphog** [comment]
- https://crates.io/crates/mdns - doesn't look very actively maintained or used
- https://crates.io/crates/libp2p-mdns - pulls in a bunch of libp2p core stuff we probably don't want

It may make the most sense to write our own thin UDP wrapper over https://crates.io/crates/dns-parser to provide mdns spec. Can test against something like https://www.npmjs.com/package/multicast-dns to verify functionality.

**Comment by neonphog** [comment]
Prototype code: https://github.com/holochain/lib3h/compare/mdns
