### ISSUE TITLE
HBC Message Receiving Using DHT

### ISSUE THREAD

**Issue by neonphog** [holochain/lib3h#66]
HBC will need to poll for messages periodically on the current anchor (and probably some number of previous anchors... we can start with just 1 previous one).

HBC will need to generate the anchor strings it wants to poll on and make a request to `fetch` them... then time sort all the meta items that are of "message" type, and display them.

Note: for the CLI interface, it may make the most sense to keep track a "last_message_timestamp" and only display messages > than that, since we can't easily go back and edit the scrollback history.

**Comment by jmday** [comment]
In a distributed context, I'd be concerned about a strict use of message timestamps > X as messages will likely come in with with timestamp < X after a message with timestamp X is viewed.

**Comment by neonphog** [comment]
@jmday 

This would be strictly an interface quirk, since we cannot go back and modify history in a terminal. We could go and display them out of order... but in a chat context it might be confusing.
