### ISSUE TITLE
logging is separated into front and back-end

### ISSUE THREAD

**Issue by zippy** [holochain/lib3h#96]
## Story
As a user of the logging crate, I have separate access to front-end and back-end, so that front-end generation of log messages in code is not conflated with where those messages are received at run-time.

## Tasks
-[ ] separate functions that allow creation of logging messages into a logical  "front-end" component
-[ ] separate functions that receive logged messages for filtering, and then for passing to an output channel, into "back-end" component
-[ ] convert lib3h library code to use the front-end, and lib3h testing binaries to use the back-end
-[ ] add use of "back-end" into holochain-core conductor.

### acceptance criteria
- there is a test that shows using the lib3h library where logging messages are not captured by any back-end and thus are simply discarded
- there is a test that shows using the lib3h library where logging messages are captured by a sample testing in-memory back-end receiver.
- there is a test that demostrates that the back-end can be specified per logging context.

## [Requirements HackMD](https://hackmd.io/MP5F3UhSTp2iPk37Cwa-fw?both)

**Comment by jmday** [comment]
How could logging messages to the front-end component/receiver be tested (if testing always sends logging to the back-end receiver)? Is there an appropriate acceptance criteria for this?
