### ISSUE TITLE
add global context macro for accessing logging front-end in lib3h

### ISSUE THREAD

**Issue by zippy** [holochain/lib3h#97]
##  Story
As a lib3h coder I can use a macro for easy global logging which uses the same crate and so that logging gets configured by the lib3h user but I can write logging messages cleanly and simply

### tasks
- Create macros for a "global" networking context for log levels:
    - notify, warn, debug, trace
- Create a source for the configuration of this networking "global" context
### acceptance criteria
- we have tests that show that logging is working as configured at the networking level by showing different networking logging configurations produce different logging outputs.

## [Requirements HackMD](https://hackmd.io/MP5F3UhSTp2iPk37Cwa-fw?both)

**Comment by jmday** [comment]
I may not know enough about the background here, but... Will having macros for a "global" networking context lead to less granular log output management capabilities (i.e. if it's just easier to use the macro than create a more appropriate local context)? Or, could a macro incorporate the use of local contexts as well?

**Comment by zippy** [comment]
This got simplified by just using the log crate facade.
